#!/bin/bash
set -e

CURRENTDIR=$(pwd)

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

git submodule update --init --recursive

# Install the ROS master
# cd $CURRENTDIR/ros_master/social_interaction
# exec ./INSTALL

# Install the brain
# cd $CURRENTDIR/brain/social_interaction
# exec ./INSTALL

cd $CURRENTDIR
