#!/bin/bash
set -e

CURRENTDIR=$(pwd)
HOSTNAME="brain_node"

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Update all packages
git submodule update --init --recursive

# Change the hostname
sed -i "/raspberrypi/$HOSTNAME" /etc/hosts
echo $HOSTNAME >> /etc/hostname
echo $HOSTNAME >> /boot/hostnames
echo "Hostname changed to $HOSTNAME"

# Install the ROS master
cd $CURRENTDIR/ros_master/social_interaction
exec ./INSTALL

# Install the brain
cd $CURRENTDIR/brain/social_interaction
exec ./INSTALL

cd $CURRENTDIR
