#!/bin/bash
# /etc/init.d/willy
#

cd /opt/willy

case "$1" in
start)
  exec ./components/ros_master/START start &>/dev/null &
  exec ./components/brain/START start &>/dev/null &
  ;;
stop)
  exec ./components/ros_master/START stop &>/dev/null &
  exec ./components/brain/START stop &>/dev/null &
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
