#!/bin/bash
### BEGIN INIT INFO
# Provides: willy
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description:  Enable willy processes
### END INIT INFO

cd /opt/willy

case "$1" in
start)
  exec ./components/ros_master/START start &>/dev/null &
  exec ./components/brain/START start &>/dev/null &
  ;;
stop)
  exec ./components/ros_master/START stop &>/dev/null &
  exec ./components/brain/START stop &>/dev/null &
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
