#!/bin/bash
# /etc/init.d/willy
#


cd /opt/willy

case "$1" in
start)
  exec ./components/ros_master/START start
  exec ./components/brain/START start
  ;;
stop)
  exec ./components/ros_master/START stop
  exec ./components/brain/START stop
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
